using System;
using System.Collections.Generic;
using Terraria;
using Terraria.ID;
using TShockAPI;

namespace AntiCheatingTool;

internal static class BoundaryBuilder
{
    private const int WallHeight = 80;
    private const int GroundGateHeight = 20;
    private const int AirGateBottom = 45;
    private const int AirGateHeight = 25;
    private const int WallThickness = 3;
    private const int SearchAbove = 140;
    private const int SearchBelow = 180;

    private static readonly HashSet<long> BorderTiles = new();

    public static int Count => BorderTiles.Count;

    public static bool Contains(int x, int y) => BorderTiles.Contains(Key(x, y));

    public static bool IsNearBoundary(int x, int y, int margin)
    {
        for (var dx = -margin; dx <= margin; dx++)
        {
            for (var dy = -margin; dy <= margin; dy++)
            {
                if (Contains(x + dx, y + dy))
                {
                    return true;
                }
            }
        }

        return false;
    }

    public static void Build(Config cfg)
    {
        if (cfg?.Protection == null || Main.tile == null || Main.maxTilesX <= 0 || Main.maxTilesY <= 0)
        {
            return;
        }

        ClearKnown();
        var spawnX = ProtectionZone.SpawnTileX;
        var spawnY = ProtectionZone.SpawnTileY;
        var radius = Math.Max(1, cfg.Protection.SpawnXRadius);
        var leftX = spawnX - radius;
        var rightX = spawnX + radius;
        var leftSurface = FindSurfaceY(leftX, spawnY);
        var rightSurface = FindSurfaceY(rightX, spawnY);
        var oldRoofY = Math.Min(leftSurface, rightSurface) - WallHeight;

        // Remove the old experimental roof line if this world was generated by an earlier build.
        for (var x = leftX; x <= rightX; x++)
        {
            RemoveIfBorder(x, oldRoofY);
        }

        BuildSideWall(leftX, leftSurface);
        BuildSideWall(rightX, rightSurface);

        TShock.Log.ConsoleInfo($"[AntiCheatingTool] 保护区边框已刷新：警戒物块 {BorderTiles.Count} 格，地上半径 {radius}，地面通道 {GroundGateHeight} 格，空中通道 {AirGateHeight} 格。");
    }

    private static void BuildSideWall(int centerX, int surfaceY)
    {
        for (var offset = -(WallThickness / 2); offset <= WallThickness / 2; offset++)
        {
            var x = centerX + offset;
            for (var y = surfaceY - WallHeight; y <= surfaceY - 1; y++)
            {
                var height = surfaceY - y;
                var inGroundGate = height <= GroundGateHeight;
                var inAirGate = height > AirGateBottom && height <= AirGateBottom + AirGateHeight;
                if (inGroundGate || inAirGate)
                {
                    RemoveIfBorder(x, y);
                    continue;
                }

                Place(x, y);
            }
        }
    }

    private static int FindSurfaceY(int x, int fallbackY)
    {
        if (x < 0 || x >= Main.maxTilesX || Main.tileSolid == null)
        {
            return fallbackY;
        }

        var start = Math.Max(1, fallbackY - SearchAbove);
        var end = Math.Min(Main.maxTilesY - 2, fallbackY + SearchBelow);
        for (var y = start; y <= end; y++)
        {
            var tile = Main.tile[x, y];
            if (tile != null && tile.active() && tile.type != TileID.RedBrick && tile.type < Main.tileSolid.Length && Main.tileSolid[tile.type])
            {
                return y;
            }
        }

        return fallbackY;
    }

    private static void Place(int x, int y)
    {
        if (x <= 0 || x >= Main.maxTilesX - 1 || y <= 0 || y >= Main.maxTilesY - 1)
        {
            return;
        }

        var tile = Main.tile[x, y];
        if (tile == null)
        {
            tile = new Tile();
            Main.tile[x, y] = tile;
        }

        tile.active(true);
        tile.type = TileID.RedBrick;
        tile.frameX = -1;
        tile.frameY = -1;
        BorderTiles.Add(Key(x, y));
        NetMessage.SendTileSquare(-1, x, y);
    }

    private static void RemoveIfBorder(int x, int y)
    {
        if (x <= 0 || x >= Main.maxTilesX - 1 || y <= 0 || y >= Main.maxTilesY - 1)
        {
            return;
        }

        var tile = Main.tile[x, y];
        if (tile == null || !tile.active() || tile.type != TileID.RedBrick)
        {
            return;
        }

        tile.active(false);
        tile.type = 0;
        NetMessage.SendTileSquare(-1, x, y);
    }

    private static void ClearKnown()
    {
        foreach (var key in BorderTiles)
        {
            var x = (int)(key >> 32);
            var y = (int)(key & 0xffffffff);
            RemoveIfBorder(x, y);
        }

        BorderTiles.Clear();
    }

    private static long Key(int x, int y) => ((long)x << 32) | (uint)y;
}


